import fs from 'fs'
import path from 'path'
import { buildRegistry } from './registry-builder.js'
import type { ResolvedConfig } from '../types.js'

export async function generateRegistryFile(
  root: string,
  config: ResolvedConfig,
): Promise<number> {
  const registry = await buildRegistry(root, config)
  const outDir = path.join(root, '.compoviewer')

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true })
  }

  const entries = registry.components.map((c) => {
    const relPath = path
      .relative(outDir, path.resolve(root, c.filePath))
      .replace(/\\/g, '/')
    const importPath = relPath.startsWith('.') ? relPath : `./${relPath}`

    const loadExpr =
      c.exportType === 'default'
        ? `() => import('${importPath}').then(m => m.default)`
        : `() => import('${importPath}').then(m => m['${c.exportName}'])`

    return `  {
    name: ${JSON.stringify(c.name)},
    filePath: ${JSON.stringify(c.filePath)},
    exportName: ${JSON.stringify(c.exportName)},
    exportType: ${JSON.stringify(c.exportType)},
    props: ${JSON.stringify(c.props)},
    load: ${loadExpr},
  }`
  })

  const content = `// Auto-generated by react-compoviewer — do not edit
// Generated at ${new Date().toISOString()}

export const registry = [
${entries.join(',\n')}
];

export const config = ${JSON.stringify(
    { shortcut: config.shortcut, panel: config.panel },
    null,
    2,
  )};
`

  fs.writeFileSync(path.join(outDir, 'registry.ts'), content)
  ensureGitignore(root)

  return registry.components.length
}

function ensureGitignore(root: string) {
  const gitignorePath = path.join(root, '.gitignore')
  const entry = '.compoviewer/'

  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf-8')
    if (!content.includes(entry)) {
      fs.appendFileSync(gitignorePath, `\n${entry}\n`)
    }
  } else {
    fs.writeFileSync(gitignorePath, `${entry}\n`)
  }
}
